uport-project/uport-android-sdk

- build.gradle
- core/build.gradle
- core/src/main/java/me/uport/sdk/core/IFuelTokenProvider.kt
- did/build.gradle
- did/src/main/java/me/uport/sdk/did/DIDResolver.kt
- gradle/wrapper/gradle-wrapper.properties
- identity/build.gradle
- identity/src/main/java/me/uport/sdk/identity/AccountCreator.kt
- jsonrpc/build.gradle
- jwt/build.gradle
- jwt/src/androidTest/java/me/uport/sdk/jwt/JWTDecodeTest.kt
- jwt/src/androidTest/java/me/uport/sdk/jwt/JWTToolsTests.kt
- jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
- sdk/build.gradle
- sdk/src/main/java/me/uport/sdk/Uport.kt
- sdk/src/main/java/me/uport/sdk/signer/SimpleSigner.kt
This changeset brings a much needed update to the set of dependencies.
The most notable are:
* kethereum 0.53
* uport-android-signer 0.2.1
Along with this, the tests and code that broke after the update have been adapted to fit the new APIs.
> [support] update dependencies

- demoapp/build.gradle
- demoapp/src/main/java/me/uport/sdk/demoapp/DemoApplication.kt
- identity/src/main/java/me/uport/sdk/identity/Account.kt
- identity/src/main/java/me/uport/sdk/identity/AccountCreator.kt
- identity/src/main/java/me/uport/sdk/identity/KPAccountCreator.kt
- identity/src/main/java/me/uport/sdk/identity/MetaIdentityAccountCreator.kt
- sdk/src/main/java/me/uport/sdk/Transactions.kt
- sdk/src/main/java/me/uport/sdk/Uport.kt
- sdk/src/main/java/me/uport/sdk/extensions/TransactionExtensions.kt
As the uPort targets shift, so must the libraries.
This changeset makes the default account created by the SDK a simple `KeyPair` account instead of a `MetaIdentityManager`-proxy contract account.
This is a breaking change.
There is no need to include the fuelingservice anymore since KP accounts have to be self-funded.
> Default to KeyPair account

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- sdk/src/androidTest/java/me/uport/sdk/UportTest.kt
- sdk/src/main/java/me/uport/sdk/Uport.kt
On initial account creation, `Uport.defaultAccount` only gets updated after an app restart (#11)
This PR includes a test to validate this scenario and a fix for the bug
Run `./gradlew :sdk:cC` with an emulator/device connected. It should also go through the respective test.
> update default account after creation

- identity/build.gradle
- identity/src/androidTest/java/KPAccountCreatorTest.kt
- identity/src/main/java/me/uport/sdk/identity/AccountCreator.kt
- identity/src/main/java/me/uport/sdk/identity/KPAccountCreator.kt
- identity/src/main/java/me/uport/sdk/identity/MetaIdentityAccountCreator.kt
- sdk/src/androidTest/java/me/uport/sdk/UportTest.kt
- sdk/src/main/java/me/uport/sdk/Uport.kt
For recovery purposes, the SDK must provide a way to create accounts from a seed phrase.
This PR fixes #7 by allowing `Uport.createAccount` to receive a seed phrase and exposing an `importAccount` in the `AccountCreator` interface in the `identity` module
I added tests to cover the new functionality.
They can be run by `./gradlew cC` with a device/emulator connected.
> Add option to import seeds

- identity/src/main/java/me/uport/sdk/identity/AccountCreator.kt
- identity/src/main/java/me/uport/sdk/identity/KPAccountCreator.kt
- identity/src/main/java/me/uport/sdk/identity/MetaIdentityAccountCreator.kt
- sdk/src/androidTest/java/me/uport/sdk/UportTest.kt
- sdk/src/main/java/me/uport/sdk/Uport.kt
This changeset adds `deleteAccount` functionality.
Since the SDK is using HD accounts, the actual thing being deleted is the seed from protected storage.
If the account being deleted is the default one, that is cleared as well.
with an emulator / device connected, simply run `./gradlew cC` which will run the entire instrumented test suite including the test for account deletion
> [feature] add option to delete account

- identity/src/main/java/me/uport/sdk/identity/Account.kt
- identity/src/test/java/me/uport/sdk/identity/AccountSerializationTests.kt
- identity/src/test/java/me/uport/sdk/identity/AccountsTests.kt
- jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
- sdk/build.gradle
- sdk/src/androidTest/java/me/uport/sdk/UportTest.kt
- sdk/src/main/java/me/uport/sdk/AccountStorage.kt
- sdk/src/main/java/me/uport/sdk/Uport.kt
- sdk/src/test/java/me/uport/sdk/AccountStorageTest.kt
- sdk/src/test/java/me/uport/sdk/fakes/InMemoryAccountStorage.kt
- sdk/src/test/java/me/uport/sdk/fakes/InMemorySharedPrefs.kt
- signer/build.gradle
- signer/src/androidTest/java/com/uport/sdk/signer/HDSignerTests.kt
- signer/src/androidTest/java/com/uport/sdk/signer/SignatureTests.kt
- signer/src/androidTest/java/com/uport/sdk/signer/SignerTests.kt
- signer/src/androidTest/java/com/uport/sdk/signer/UserInteractionContextTests.kt
- signer/src/main/java/com/uport/sdk/signer/Extensions.kt
- signer/src/main/java/com/uport/sdk/signer/UportHDSigner.kt
- signer/src/main/java/com/uport/sdk/signer/UportSigner.kt
This brings support for multiple accounts in the SDK (fix for #15).
* added AccountStorage that can hold multiple accounts.
* there can be only one default account
* `Uport.defaultAccount` behaves the same, but is now a property (w `get()`/`set()`)
* added `Uport.getAccount(handle)`
* added `Uport.allAccounts()`
* when default account is deleted, other accounts can remain but are not automatically promoted to default.
Just run `./gradlew test cC` with an emulator/device connected.
> Add support for multiple accounts

- README.md
- build.gradle
- credentials/src/test/java/me/uport/sdk/credentials/CredentialsTest.kt
- jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
- jwt/src/test/java/JWTToolsJVMTest.kt
- signer/build.gradle
- signer/src/androidTest/java/com/uport/sdk/signer/HDSignerTests.kt
- signer/src/androidTest/java/com/uport/sdk/signer/SignerTests.kt
- signer/src/androidTest/java/com/uport/sdk/signer/UserInteractionContextTests.kt
- signer/src/main/java/com/uport/sdk/signer/Extensions.kt
- signer/src/main/java/com/uport/sdk/signer/KPSigner.kt
- signer/src/main/java/com/uport/sdk/signer/UportHDSigner.kt
- signer/src/main/java/com/uport/sdk/signer/UportSigner.kt
- signer/src/test/java/com/uport/sdk/signer/crypto/bip32/DerivationTest.kt
- signer/src/test/java/com/uport/sdk/signer/crypto/bip32/ExtendedKeyTest.kt
- signer/src/test/java/com/uport/sdk/signer/crypto/bip39/MnemonicTest.kt
This is a long overdue update of a bunch of dependencies, most importantly of kethereum.
The key derivation API and handling of mnemonic phrases has changed in kethereum, requiring a review of several classes and tests.
The `signer` module has the most changes since it dealt most with this API.
The whole battery of tests should be run.
Use `./gradlew clean test cC` with at least one emulator/device connected.
None of the test data has changed so this should reflect identical functionality.
> [Support] bump kethereum to 63

- ethr-did/src/main/java/me/uport/sdk/ethrdid/EthrDID.kt
- jwt/src/androidTest/java/me/uport/sdk/jwt/JWTSignerAlgorithmRuntimeTest.kt
- jwt/src/androidTest/java/me/uport/sdk/jwt/JWTToolsTests.kt
- jwt/src/test/java/me/uport/sdk/jwt/JWTSignerAlgorithmTest.kt
- sdk/build.gradle
- signer/src/main/java/com/uport/sdk/signer/Extensions.kt
- transport/src/androidTest/AndroidManifest.xml
- transport/src/main/java/me/uport/sdk/transport/Transports.kt
This fixes #42
This fixes [#161565476] from pivotal.
The recovery parameter of a `SignatureData` is either 27 or 28 but when it is used to recover public keys from signatures it should be 0 or 1.
JWTs created by this SDK should be verifiable across platforms, including [did-jwt] (https://github.com/uport-project/did-jwt)
For this reason, the recovery param has to be encoded as 0 or 1 in the buffer representing the signature of JWTs
The key part of this changeset is in `Extensions.kt`, all the other changes involve tests and test data that needs to be adapted to the new format.
A test was added to check for this scenario.
Running it in commit [b69eb9c](https://github.com/uport-project/uport-android-sdk/commit/b69eb9c7df27ab1ac852f39e64ce27c572b7d2bd) should fail.
To run the entire battery …
> [bugfix] recovery param jose encoding

- signer/src/main/java/com/uport/sdk/signer/storage/ProtectedSharedPreferences.kt
This is a fix for some of the warnings thrown during build.
No functionality change, just telling kotlin that defaults are non-null.
`./gradlew test cC` with an emulator connected
Some warnings are still showing but will disappear after #37 is fixed
> [support] fix warnings in ProtectedSharedPreferences

- jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
- jwt/src/test/java/me/uport/sdk/jwt/KeyRecoveryTest.kt
I added a test to do a lot of signJWT calls and recover the public keys from the signatures.
The test goes through 1000000 combinations of keys and messages.
I found no combination that produces bad signatures so I commented out the test because it takes 15-20 minutes at least but left it there for sanity checks.
This closes [#162137904](https://www.pivotaltracker.com/story/show/162137904) on pivotal.
uncomment line 17 in `KeyRecoveryTest.kt` and run it in android studio or with `./gradlew :jwt:testDebug` to see it in action
> [Bugfix] 162137904 jwt signature recovery

- jwt/src/androidTest/java/me/uport/sdk/jwt/JWTToolsTests.kt
- jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
- jwt/src/test/java/me/uport/sdk/jwt/JWTToolsJVMTest.kt
- jwt/src/test/java/me/uport/sdk/jwt/model/TestTimeProvider.kt
Pivotal Tracker: https://www.pivotaltracker.com/story/show/162662579
Throws `InvalidJWTException` when the current time via the TimeProvider is not within the range of `iat` and `exp`
JVM Tests have been added and can be run using ./gradlew :jwt:test
The full suite can be run with ./gradlew clean test cC --no-parallel with a device/emultator connected
> [Bug] Verify JWT timestamp

- build.gradle
- demoapp/src/main/java/me/uport/sdk/demoapp/DeepLinkActivity.kt
- demoapp/src/main/res/layout/activity_deep_link.xml
- jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
- transport/build.gradle
- transport/src/main/java/me/uport/sdk/transport/ResponseParser.kt
- transport/src/test/java/me/uport/sdk/transport/IntentParserTest.kt
- transport/src/test/java/me/uport/sdk/transport/ResponseParserTest.kt
- universal-did/src/main/java/me/uport/sdk/universaldid/UniversalDID.kt
The bulk of this PR is the `ResponseParser` class that is able to extract `shareResp` JWTs from deep link replies.
Selective disclosure replies come in as deepLink URIs into a "router activity" that the developer is supposed to implement (The sample app it is called `DeeplinkActivity.kt`).
The 2 methods exposed enable devs to extract JWTs either directly from the `Intent` object received by the router activity or from an already processed URI (for more complex routing logic)
The demoapp has been updated to demonstrate a selective disclosure flow where the `name` field is requested from the uPort app and the response parsed and displayed.
JVM Tests have been added and can be run using `./gradlew :transport:test`
The full suite can be run with `./gradlew clean test cC --no-parallel` with a …
> [Feature] parse selective disclosure response uri

- demoapp/src/main/java/me/uport/sdk/demoapp/VerifyJWTActivity.kt
- jwt/src/androidTest/java/me/uport/sdk/jwt/JWTToolsTests.kt
- jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
- jwt/src/test/java/me/uport/sdk/jwt/JWTToolsJVMTest.kt
Solution to the User Story https://www.pivotaltracker.com/story/show/162701140
Improve exception handling in `JWTTools.verify()` by throwing specific errors and not returning null 
One test added to `JWTToolsTest`
Run using the command ./gradlew clean jwt:test cC --no-parallel when connected to an emulator
> JWT Verification Exception Handling

- identity/build.gradle
- identity/src/main/java/me/uport/sdk/identity/Account.kt
- identity/src/test/java/me/uport/sdk/identity/AccountsTests.kt
This provides a function which allows developers access the DID associated with accounts created via uPort. More details can be found in the US https://www.pivotaltracker.com/story/show/162697134
3 JVM tests added to `AccountTests`
Run with `./gradlew :identity:test`
> Feature/Connecting a DID to an Account

- .gitignore
- build.gradle
- core/build.gradle
- credentials/build.gradle
- ethr-did/build.gradle
- fuelingservice/build.gradle
- https-did/build.gradle
- identity/build.gradle
- jsonrpc/build.gradle
- jwt/build.gradle
- publishing.gradle
- sdk/build.gradle
- serialization/build.gradle
- signer/build.gradle
- transport/build.gradle
- universal-did/build.gradle
- uport-did/build.gradle
This PR adds the configuration needed for publishing the sdk libraries to a maven repo.
This fixes [#162411452](https://www.pivotaltracker.com/story/show/162411452) from pivotal as well.
Developers can click through SDK sources right from android studio.
> add maven publishing configuration

- transport/src/main/java/me/uport/sdk/transport/ResponseParser.kt
- transport/src/test/java/me/uport/sdk/transport/ResponseParserTest.kt
Added support for parsing the response from several types of requests as described in https://www.pivotaltracker.com/story/show/163297105
- Updated the regex to match keys for `verification`, `typedDataSig`, `personalSig`, `tx`
- Added tests for each response type
./gradlew test cC --no-parallel
> Add support for all uPort response types

- build.gradle
- core/src/main/java/me/uport/sdk/core/Networks.kt
- credentials/src/main/java/me/uport/sdk/credentials/Credentials.kt
- credentials/src/main/java/me/uport/sdk/credentials/JWTType.kt
- credentials/src/main/java/me/uport/sdk/credentials/JWTTypes.kt
- credentials/src/main/java/me/uport/sdk/credentials/PersonalSignRequestParams.kt
- credentials/src/main/java/me/uport/sdk/credentials/SelectiveDisclosureRequestParams.kt
- credentials/src/main/java/me/uport/sdk/credentials/VerifiedClaimRequestParams.kt
- credentials/src/test/java/me/uport/sdk/credentials/CredentialsTest.kt
- demoapp/src/main/AndroidManifest.xml
- demoapp/src/main/java/me/uport/sdk/demoapp/DeepLinkActivity.kt
- demoapp/src/main/java/me/uport/sdk/demoapp/managing_jwt/VerifyJWTActivity.kt
- demoapp/src/main/java/me/uport/sdk/demoapp/request_flows/PersonalSignRequestActivity.kt
- demoapp/src/main/java/me/uport/sdk/demoapp/request_flows/VerifiedClaimRequestActivity.kt
- demoapp/src/main/res/layout/activity_deep_link.xml
- jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
- jwt/src/main/java/me/uport/sdk/jwt/model/JwtPayload.kt
- jwt/src/test/java/me/uport/sdk/jwt/JWTDecodeTest.kt
A dev building a mobile frontend that interacts with the uPort mobile app should be able to easily create requests using self documenting abstractions instead of crafting JWTs by hand.
* `Credentials` object exposes method to build a  `verificationSignatureRequest()` and `createPersonalSignRequest()`
* parameters needed for such a request should be represented by specific data types with blank default values corresponding to the optional parameters
* sample app shows the use of these abstractions in the request flows menu (verification and personal sign submenus)
As usual, `./gradlew test cC --no-parallel` should go through the whole testsuite.
In this case successful compilation of the sampleapp is also part of the test since the request parameters data types require the obligatory …
> [Feature] define jwt types for verification and personal sign requests

- demoapp/src/main/java/me/uport/sdk/demoapp/DeepLinkActivity.kt
- jwt/src/main/java/me/uport/sdk/jwt/ECUtils.kt
- jwt/src/main/java/me/uport/sdk/jwt/JWTTools.kt
- jwt/src/test/java/me/uport/sdk/jwt/ECUtilsKtTest.kt
- jwt/src/test/java/me/uport/sdk/jwt/KeyRecoveryTest.kt
- signer/src/main/java/com/uport/sdk/signer/Extensions.kt
Verify JWTs different based on the header algorithm
- Use the filtered list of public keys from `resolveAuthenticator` instead of using the list of keys directly from the `DIDDocument` 
- Added two new methods `verifyRecoverableES256K()` and `verifyES256K` in `JWTTools`. 
Run test suite using `./gradlew test cC --no-parallel`
Note: This task is branched out from `feature/163328062-resolve-authenticator`
> Verifier Algorithm

- credentials/build.gradle
- credentials/src/main/java/me/uport/sdk/credentials/Credentials.kt
- credentials/src/test/java/me/uport/sdk/credentials/CredentialsTest.kt
A method to create a specific type of JWT which contains a claim about a subject.
Here is the JS implementation:
https://github.com/uport-project/uport-credentials/blob/0ba1060ab4c99be3de367e55c382f705f7f5d215/src/Credentials.js#L220
Run test suite using `./gradlew test cC --no-parallel`
> Create a signed claim about a user 

- build.gradle
- demoapp/build.gradle
- demoapp/src/androidTest/java/me/uport/sdk/demoapp/CreateAccountTest.kt
- demoapp/src/androidTest/java/me/uport/sdk/demoapp/PersonalSignatureTest.kt
- demoapp/src/androidTest/java/me/uport/sdk/demoapp/SelectiveDisclosureFlowTest.kt
- demoapp/src/androidTest/java/me/uport/sdk/demoapp/TransactionRequestTest.kt
- demoapp/src/androidTest/java/me/uport/sdk/demoapp/TypedDataTests.kt
- demoapp/src/androidTest/java/me/uport/sdk/demoapp/VerifiedClaimTest.kt
- demoapp/src/androidTest/java/me/uport/sdk/demoapp/VerifyJWTTest.kt
This PR eliminates most of the `Thread.sleep()` calls from UI tests by deferring to an `Espresso` `IdlingResource` tied to the visibility of the progress bar.
There's also a bump in the version of `mockk` that clears an annoying warning.
Run `./gradlew :demoapp:cC --no-parallel` with device(s) and/or emulator(s) connected.
> [support] reduce ui test flakiness

- credentials/src/main/java/me/uport/sdk/credentials/Credentials.kt
- credentials/src/test/java/me/uport/sdk/credentials/CredentialsTest.kt
- jwt/src/main/java/me/uport/sdk/jwt/JWTExceptions.kt
This PR adds a feature which authenticates the response from a selective disclosure request by 
If any of the above is not satisfied a `JWTAuthenticationException` is thrown
This solves https://www.pivotaltracker.com/story/show/164105045
Run gradle command `./gradlew test cC --no-parallel`
> Authenticating a Selective Disclosure Response
